### ISSUE TITLE
Not an issue but no forum or discussions are avail...

### ISSUE THREAD

**Issue by codingwithscissors** [Silversunset01/dbm#28]
I am interested in setting up a "auth bot" that will compare new xyz user's discord username with a website's player name data.

Ex:
https://robertsspaceindustries.com/citizens/icey842

Is it possible to compare the discord username and the id after /citizens/
and either accept it or reject it with a message?
Great work on the bot! Much appreciated m8

**Comment by Silversunset01** [comment]
Is this a general question for a discord bot or DBM specifically? (DBM is a program on steam that allows you to make discord bots with little coding experience).

**Comment by codingwithscissors** [comment]
sry....dbm specifically

**Comment by codingwithscissors** [comment]
> sry....dbm specifically

Omg...I just remembered that Discord id's hashtag out to unique numbering. So this will never match and I have no need to compare both I guess. Maybe I will just stick to authorizing their accounts via their star citizen account page usernames. Well sorry for the waste of your time lol but thanks for the reply silversun!
