### ISSUE TITLE
Keybindings

### ISSUE THREAD

**Issue by ReshiStar** [Silversunset01/dbm#30]
So if i've pieced this together correctly, there's unlabeled keybindings that cannot be modified and has no actual documentation, regarding the F1-12 keys, such as a quicksave and quickload. Can you please either add a way to change this stuff, label this information or perhaps remove it? Its extremely frustrating to spend days on a bot only to accidentally undo it all and save over it because i was changing the song i was listening to.

**Comment by Silversunset01** [comment]
This is not the place to submit bugs. Please join the discord server, access the forums, or visit dbm-support.site
