### ISSUE TITLE
Find current voice channel by member id

### ISSUE THREAD

**Issue by ad1k4h** [Silversunset01/dbm#31]
Dear all,

I would like to Get the current voice channel by member ID.
So, if a member (id) connects to a channel A, the bot triggered, joined, etc..
if the member goes to channel B, the bot join to the channel B.
I can find the member by ID, but cant find the voice channel with member ID.

**Comment by Silversunset01** [comment]
This is not the place to submit help requests. Please join the discord server, access the forums, or visit dbm-support.site
