### ISSUE TITLE
TypeError: Cannot read property 'push' of undefined on "Add Item to List", Action #2

### ISSUE THREAD

**Issue by tsargoth** [Silversunset01/dbm#43]
Hello, I'm hoping someone might be able to help me with some troubleshooting please.
I'm trying to define a list of text 'sayings' and have my bot randomly choose from this list
I've added a command to 'Add To List' and the end position.
From the console when Running I get the following Type Error
Error with the command "Add Item to List", Action #2:TypeError: list.push is not a function
For reference I'm running node on a linux centos server v11.6.0

**Comment by Silversunset01** [comment]
This is not the place to submit help requests. Please join the discord server, access the forums, or visit dbm-support.site
